image: Visual Studio 2017

# save the cache even if the build fails
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.5.3\bin;%JAVA_HOME%\bin;%PATH%
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set
  - mvn clean package --batch-mode -DskipTest -Dmaven.javadoc.skip=true
test_script:
  - mvn clean install --batch-mode -Dmaven.javadoc.skip=true
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
